"""Revision planning task that produces approval-gated script artifacts."""

from __future__ import annotations

import json
import re
from pathlib import Path

from paths import translate_path
from tasks.plugin_dependencies import build_dependency_warnings
from workstation import detect_workstation_profile


def parse_changes(raw_notes: str) -> list[dict]:
    changes = []
    for sentence in re.split(r"[.\n]+", raw_notes):
        text = sentence.strip()
        if not text:
            continue
        lower = text.lower()
        element = next((item for item in ("vocals", "kick", "bass", "snare", "synth", "pads", "drums") if item in lower), "mix")
        parameter = "other"
        if "quiet" in lower or "loud" in lower or "level" in lower:
            parameter = "level"
        elif "eq" in lower or "muddy" in lower or "bright" in lower:
            parameter = "eq"
        elif "reverb" in lower:
            parameter = "reverb"
        elif "width" in lower or "wide" in lower:
            parameter = "stereo_width"
        direction = "adjust"
        if any(token in lower for token in ("up", "more", "raise", "louder")):
            direction = "up"
        elif any(token in lower for token in ("down", "less", "lower", "quieter")):
            direction = "down"
        confidence = 0.9 if parameter != "other" and element != "mix" else 0.55
        changes.append(
            {
                "element": element,
                "section": "full track",
                "parameter": parameter,
                "direction": direction,
                "value": None,
                "value_range": ["+1dB", "+3dB"] if direction == "up" else ["-3dB", "-1dB"],
                "confidence": confidence,
                "human_readable": text,
                "requires_clarification": confidence < 0.65,
            }
        )
    return changes


def _reascript_body(changes: list[dict], session_path: str | None) -> str:
    lines = [
        "-- Generated by ai-audio-studio",
        "-- Preview-oriented ReaScript scaffold",
        f"-- Session: {session_path or 'unknown'}",
        "",
        "local function log(msg)",
        "  reaper.ShowConsoleMsg(tostring(msg) .. '\\n')",
        "end",
        "",
        "reaper.Undo_BeginBlock()",
        "log('Starting generated revision pass')",
    ]
    for index, change in enumerate(changes, start=1):
        param = change.get("parameter", "other")
        direction = change.get("direction", "adjust")
        track_idx = int(change.get("track_index", 0))
        raw_value = change.get("value")
        if raw_value is None:
            db_delta = 1.5 if direction == "up" else -1.5 if direction == "down" else 0.0
        else:
            db_delta = float(raw_value)

        human_readable = change.get("human_readable", param)
        element = change.get("element", "unknown")
        lines.append(f"log('Change {index}: {human_readable}')")
        lines.append(f"-- element: {element}, parameter: {param}, direction: {direction}")
        lines.append(f"local track_{index} = reaper.GetTrack(0, {track_idx})")
        lines.append(f"if track_{index} then")
        if param in ("volume", "level"):
            linear = round(10 ** (db_delta / 20), 6)
            lines.append(f"  reaper.SetMediaTrackInfo_Value(track_{index}, 'D_VOL', {linear})")
        elif param == "pan":
            pan_val = round(max(-1.0, min(1.0, db_delta / 100.0)), 6)
            lines.append(f"  reaper.SetMediaTrackInfo_Value(track_{index}, 'D_PAN', {pan_val})")
        elif param == "mute":
            lines.append(f"  reaper.SetMediaTrackInfo_Value(track_{index}, 'B_MUTE', {1 if db_delta != 0 else 0})")
        elif param == "solo":
            lines.append(f"  reaper.SetMediaTrackInfo_Value(track_{index}, 'I_SOLO', {1 if db_delta != 0 else 0})")
        else:
            lines.append(f"  -- Unsupported parameter: {param}")
        lines.append(f"  reaper.UpdateArrange()")
        lines.append(f"end")
        lines.append("")
    lines.extend(
        [
            "reaper.Undo_EndBlock('AI Audio Studio revision scaffold', -1)",
            "log('Revision scaffold finished')",
        ]
    )
    return "\n".join(lines) + "\n"


def _soundflow_body(changes: list[dict], session_path: str | None) -> str:
    script = {
        "metadata": {
            "generated_by": "ai-audio-studio",
            "session_path": session_path,
            "change_count": len(changes),
        },
        "steps": [
            {
                "action": "comment",
                "text": change["human_readable"],
                "element": change["element"],
                "parameter": change["parameter"],
                "direction": change["direction"],
            }
            for change in changes
        ],
    }
    return json.dumps(script, indent=2) + "\n"


def write_revision_artifacts(session_dir: Path, daw: str, changes: list[dict], session_path: str | None) -> dict:
    normalized_path = session_dir / f"{daw}_revision_changes.json"
    normalized_path.write_text(json.dumps(changes, indent=2))

    if daw == "reaper":
        script_path = session_dir / "reaper_revision_script.lua"
        script_path.write_text(_reascript_body(changes, session_path))
    else:
        script_path = session_dir / "protools_revision_script.json"
        script_path.write_text(_soundflow_body(changes, session_path))

    return {
        "changes_path": str(normalized_path),
        "script_path": str(script_path),
    }


def generate_revision_artifacts(payload: dict, settings) -> dict:
    project_slug = payload["project_slug"]
    shared_root = translate_path(
        payload.get("shared_projects_path", settings.shared_projects_path),
        settings.path_translation_json,
        settings.worker_platform,
    )
    session_dir = shared_root / project_slug / "session"
    session_dir.mkdir(parents=True, exist_ok=True)
    changes = parse_changes(payload["raw_notes"])
    artifact_paths = write_revision_artifacts(session_dir, payload["daw"], changes, payload.get("session_path"))
    return {
        "changes": changes,
        "plugin_warnings": build_dependency_warnings(payload["daw"], detect_workstation_profile(settings), changes=changes),
        **artifact_paths,
    }
